//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamWeddsManager.Domain.Entities.DreamWedds
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrideAndMaid : AuditableEntity<int>
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public int WeddingID { get; set; }
        public bool IsBride { get; set; }
        public Nullable<int> RelationWithBride { get; set; }

        public string fbUrl { get; set; }
        public string googleUrl { get; set; }
        public string instagramUrl { get; set; }
        public string lnkedinUrl { get; set; }
    
        public virtual Wedding Wedding { get; set; }
    }
}
