//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamWeddsManager.Domain.Entities.DreamWedds
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeddingTemplate : AuditableEntity<int>
    {
        public WeddingTemplate()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.TemplateImages = new HashSet<TemplateImage>();
            this.TemplateMergeFields = new HashSet<TemplateMergeField>();
            //this.TemplatePages = new HashSet<TemplatePage>();
            this.UserWeddingSubscriptions = new HashSet<UserWeddingSubscription>();
        }
   
        public string Name { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public string Content { get; set; }
        public string Subject { get; set; }
        public string Tags { get; set; }
        public string TemplateUrl { get; set; }
        public string TemplateFolderPath { get; set; }
        public string ThumbnailImageUrl { get; set; }
        public string TagLine { get; set; }
        public Nullable<int> Cost { get; set; }
        public string AuthorName { get; set; }
        public string AboutTemplate { get; set; }
        public string Features { get; set; }
      
        public Nullable<int> TemplateCode { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<TemplateImage> TemplateImages { get; set; }
        public virtual ICollection<TemplateMergeField> TemplateMergeFields { get; set; }
        //public virtual ICollection<TemplatePage> TemplatePages { get; set; }
        public virtual ICollection<UserWeddingSubscription> UserWeddingSubscriptions { get; set; }
    }
}
