//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamWeddsManager.Domain.Entities.DreamWedds
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateImage
    {
        public int ImageID { get; set; }
        public string ImageName { get; set; }
        public string ImageTitle { get; set; }
        public string ImageTagLine { get; set; }
        public string ImageUrl { get; set; }
        public string ImageFolderPath { get; set; }
        public bool IsBannerImage { get; set; }
        public int TemplateID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ImageType { get; set; }
    
        public virtual WeddingTemplate TemplateMaster { get; set; }
    }
}
