//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamWeddsManager.Domain.Entities.DreamWedds
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMergeField : AuditableEntity<int>
    {
        public string MERGEFIELD_NAME { get; set; }
        public string SRC_FIELD { get; set; }
        public string SRC_FIELD_VALUE { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> TemplateCode { get; set; }
    
        public virtual WeddingTemplate TemplateMaster { get; set; }
    }
}
