//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamWeddsManager.Domain.Entities.DreamWedds
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedding : AuditableEntity<int>
    {
        public Wedding()
        {
            this.BrideAndMaids = new HashSet<BrideAndMaid>();
            this.GroomAndMen = new HashSet<GroomAndMan>();
            this.RSVPDetails = new HashSet<RSVPDetail>();
            this.TimeLines = new HashSet<TimeLine>();
            this.UserWeddingSubscriptions = new HashSet<UserWeddingSubscription>();
            this.WeddingEvents = new HashSet<WeddingEvent>();
            this.WeddingGalleries = new HashSet<WeddingGallery>();
        }
        public System.DateTime WeddingDate { get; set; }
        public string Title { get; set; }
        public int WeddingStyle { get; set; }
        public string IconUrl { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public bool IsLoveMarriage { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool IsActive { get; set; }
        public string BackgroundImage { get; set; }
        public string Quote { get; set; }
        public string fbPageUrl { get; set; }
        public string videoUrl { get; set; }
    
        public virtual ICollection<BrideAndMaid> BrideAndMaids { get; set; }
        public virtual ICollection<GroomAndMan> GroomAndMen { get; set; }
        public virtual ICollection<RSVPDetail> RSVPDetails { get; set; }
        public virtual ICollection<TimeLine> TimeLines { get; set; }
        public virtual ICollection<UserWeddingSubscription> UserWeddingSubscriptions { get; set; }
        public virtual ICollection<WeddingEvent> WeddingEvents { get; set; }
        public virtual ICollection<WeddingGallery> WeddingGalleries { get; set; }
    }
}
